import { useEffect } from 'react'
import type { ReactElement } from 'react'
import type { SiteContent } from '../types/content'
import { useLang } from '../hooks/useLang'
import { useTheme } from '../hooks/useTheme'
import './InstitutionalSite.css'
import './InstitutionalFixes.css'

export type InstitutionalRoute = 'home' | 'lab' | 'research' | 'methods' | 'systems' | 'publications' | 'observatory' | 'notes' | 'applied-research'

const BASE = import.meta.env.BASE_URL
const href = (route: InstitutionalRoute) => `${BASE}${route === 'home' ? '' : `${route}/`}`

const domains = [
  ['01', 'Komplexe Systeme & Emergenz', 'Complex Systems & Emergence', 'Rückkopplung, Selbstorganisation, Zustandsübergänge und nichtlineare Dynamik.', 'Feedback, self-organization, state transitions and nonlinear dynamics.'],
  ['02', 'Behavioral Intelligence', 'Behavioral Intelligence', 'Verhaltensmuster, Drift, Entscheidungen und Veränderungen über Zeit.', 'Behavioral patterns, drift, decisions and change over time.'],
  ['03', 'Systemrekonstruktion', 'System Reconstruction', 'Tatsächliche Systemstruktur aus fragmentierter Evidenz ableiten.', 'Inferring actual system structure from fragmented evidence.'],
  ['04', 'Mensch–KI-Dynamik', 'Human–AI Dynamics', 'Langfristige Interaktion, Ko-Adaption, Rollenbildung und Kontextakkumulation.', 'Longitudinal interaction, co-adaptation, role formation and accumulated context.'],
  ['05', 'Systemintegrität', 'System Integrity', 'Behauptete, erwartete und beobachtete Zustände gegeneinander prüfen.', 'Testing represented, expected and observed states against one another.'],
  ['06', 'Prediction & Kausalität', 'Prediction & Causality', 'Zustandsübergänge und Gegenfaktuale unter expliziter Unsicherheit modellieren.', 'Modeling state transitions and counterfactuals under explicit uncertainty.'],
  ['07', 'Computational Research Systems', 'Computational Research Systems', 'Forschungsmethoden in operative Instrumente und Infrastrukturen übersetzen.', 'Translating research methods into operational instruments and infrastructure.'],
]

const methodStages = [
  ['Observe', 'Beobachten', 'Was geschieht tatsächlich?', 'What is actually happening?'], ['Separate', 'Trennen', 'Behauptet, erwartet, beobachtet oder unbekannt?', 'Claimed, expected, observed or unknown?'],
  ['Contextualize', 'Kontextualisieren', 'Was bedeutet die Spur in Zeit und System?', 'What does the trace mean across time and system?'], ['Correlate', 'Korrelieren', 'Welche getrennten Signale gehören zusammen?', 'Which separate signals belong together?'],
  ['Reconstruct', 'Rekonstruieren', 'Welche Struktur erklärt die Beobachtungen?', 'Which structure explains the observations?'], ['Detect', 'Widersprüche erkennen', 'Wo weichen Darstellung und Verhalten ab?', 'Where do representation and behavior diverge?'],
  ['Infer', 'Constraints ableiten', 'Welche unsichtbaren Regeln zeigt der Bruch?', 'Which hidden rules does the break reveal?'], ['Hypothesize', 'Hypothesen bilden', 'Welche Erklärungen passen zur Evidenz?', 'Which explanations fit the evidence?'],
  ['Test', 'Adversarial prüfen', 'Welche Erklärung überlebt Gegenbelege?', 'Which explanation survives counter-evidence?'], ['Model', 'Modellieren', 'Welches Modell braucht die wenigsten Annahmen?', 'Which model requires the fewest assumptions?'],
  ['Project', 'Projizieren', 'Welche Zustände werden wahrscheinlicher?', 'Which states become more likely?'], ['Monitor', 'Weiter beobachten', 'Was unterstützt oder widerlegt die Projektion?', 'What supports or contradicts the projection?'],
  ['Validate', 'Validieren', 'Gestützt, teilweise, falsifiziert oder offen?', 'Supported, partial, falsified or inconclusive?'], ['Formalize', 'Formalisieren', 'Ist das Muster stabil genug für eine Methode?', 'Is the pattern stable enough to become a method?'],
  ['Operationalize', 'Operationalisieren', 'Kann es als Instrument umgesetzt werden?', 'Can it be implemented as an instrument?'], ['Feed Back', 'Zurückführen', 'Wie verändert es die nächste Beobachtung?', 'How does it change the next observation?'],
]

const programs = [
  ['Emergent Interaction', 'FOUNDATIONAL · ACTIVE', 'Langfristige Mensch–KI-Interaktion, Ko-Adaption, Drift und emergente Strukturen.', 'Longitudinal human–AI interaction, co-adaptation, drift and emergent structures.'],
  ['Behavioral Dynamics', 'ACTIVE', 'Musterstabilität, Strategiewechsel und Verhaltenszustände.', 'Pattern stability, strategy change and behavioral states.'],
  ['System Reconstruction', 'ACTIVE', 'Rekonstruktion aus Dokumenten, Ereignissen, Code und Verhalten.', 'Reconstruction from documents, events, code and behavior.'],
  ['System Integrity', 'ACTIVE', 'Vergleich formaler Rollen und tatsächlicher Systemzustände.', 'Comparison of formal roles and actual system states.'],
  ['Computational Research Agents', 'EXPERIMENTAL', 'Operationalisierung analytischer Strukturen in Forschungsagenten.', 'Operationalizing analytical structures in research agents.'],
]

const systems = [
  ['Observatory', 'RESEARCH INSTRUMENT', 'Longitudinale Signale zu Interaktion, Drift, Rollenstabilität und Zustandsveränderung.', 'Longitudinal signals for interaction, drift, role stability and state change.', 'Emergent Interaction Lab', 'RFI-IRFOS'],
  ['lauras-team', 'RESEARCH INFRASTRUCTURE', 'Multi-Agent-Infrastruktur für spezialisierte analytische Perspektiven und wiederholbare Research Workflows.', 'Multi-agent infrastructure for specialized analytical perspectives and repeatable research workflows.', 'Laura / EIL', 'RFI-IRFOS'],
  ['Jarvis', 'AUTONOMOUS RESEARCH AGENT', 'Iterativ aus wiederkehrenden Forschungsanforderungen entstandener Agent.', 'An agent developed iteratively from recurring research requirements.', 'Laura / EIL', 'RFI-IRFOS'],
  ['Call Laura', 'ANALYTICAL SYSTEM', 'Deterministische Mehrperspektiven-Prüfung mit expliziter Attribution.', 'Deterministic multi-perspective analysis with explicit attribution.', 'Laura / EIL', 'RFI-IRFOS'],
  ['Research Knowledge Graph', 'RESEARCH INFRASTRUCTURE', 'Verbindet Entitäten, Evidenz, Ereignisse, Methoden und Forschungsartefakte.', 'Connects entities, evidence, events, methods and research artifacts.', 'Emergent Interaction Lab', 'RFI-IRFOS'],
  ['World Model', 'EXPERIMENTAL INFRASTRUCTURE', 'Strukturierte Repräsentation beobachteter Zustände und möglicher Übergänge.', 'Structured representation of observed states and possible transitions.', 'Emergent Interaction Lab', 'RFI-IRFOS'],
]

const analyticalMethods = [
  { name: 'Outside-In System Inference', type: 'METHOD', purpose: ['Systemstruktur aus unvollständigen äußeren Spuren rekonstruieren.', 'Reconstruct system structure from incomplete external traces.'], input: 'documents · events · interactions · code', operation: 'correlate → reconstruct → challenge', output: 'system map · evidence gaps · hypotheses', validation: 'source traceability · competing explanations', limits: ['Keine vollständige Innensicht; Rekonstruktionen bleiben evidenzgebunden.', 'No full internal access; reconstructions remain bounded by evidence.'] },
  { name: 'State Separation', type: 'METHOD', purpose: ['Behauptete, erwartete, beobachtete und unbekannte Zustände trennen.', 'Separate claimed, expected, observed and unknown states.'], input: 'claims · specifications · observations', operation: 'classify → compare → mark unknowns', output: 'state matrix · contradiction set', validation: 'independent source comparison', limits: ['Fehlende Evidenz ist kein Beweis für Ablehnung.', 'Missing evidence is not evidence of rejection.'] },
  { name: 'Contradiction Mapping', type: 'METHOD', purpose: ['Widersprüche lokalisieren, ohne sie vorschnell narrativ aufzulösen.', 'Locate contradictions without prematurely resolving them into a narrative.'], input: 'state matrix · timeline · sources', operation: 'link → rank → adversarial test', output: 'contradiction graph', validation: 'source-level review', limits: ['Widerspruch zeigt eine offene Erklärung, nicht automatisch Fehlverhalten.', 'A contradiction identifies an open explanation, not automatically misconduct.'] },
  { name: 'Constraint Discovery', type: 'METHOD', purpose: ['Latente Regeln aus Bruch-, Grenz- und Fehlerzuständen ableiten.', 'Infer latent rules from breakpoints, boundaries and failures.'], input: 'failures · edge cases · transitions', operation: 'compare normal/broken states', output: 'constraint hypotheses', validation: 'recurrence across cases or states', limits: ['Constraints bleiben Hypothesen, bis sie wiederholt gestützt werden.', 'Constraints remain hypotheses until repeatedly supported.'] },
  { name: 'Behavioral Drift Analysis', type: 'METHOD', purpose: ['Veränderung über längere Interaktionsverläufe als Trend untersuchen.', 'Study change across sustained interaction as a trend.'], input: 'longitudinal behavior traces', operation: 'baseline → compare → trend', output: 'drift signals · change points', validation: 'later observations', limits: ['Trend ist weder Ursache noch Vorhersage.', 'A trend is neither causation nor prediction.'] },
  { name: 'Longitudinal Validation', type: 'METHOD', purpose: ['Hypothesen und Projektionen gegen spätere Zustände prüfen.', 'Test hypotheses and projections against later states.'], input: 'dated hypothesis · later evidence', operation: 'pre-register status → monitor → classify', output: 'supported · partial · falsified · inconclusive', validation: 'timestamped comparison', limits: ['Inconclusive bleibt eine gültige Endkategorie.', 'Inconclusive remains a valid outcome.'] },
]

const frameworks = ['IEIA', 'EIA', 'UIP', 'CEI', 'LSG-24', 'LAP-1', 'LT-Data', '8-Layer Model']

const evidenceStates = [
  ['OBSERVED', 'Direkt erfasste Evidenz.', 'Directly captured evidence.'],
  ['REPORTED', 'Aussage einer identifizierten Quelle.', 'A statement from an identified source.'],
  ['DERIVED', 'Mechanisch aus Beobachtungen berechnet.', 'Mechanically computed from observations.'],
  ['INFERRED', 'Evidenzgestützte analytische Schlussfolgerung.', 'An evidence-supported analytical conclusion.'],
  ['HYPOTHESIZED', 'Prüfbare, noch nicht bestätigte Erklärung.', 'A testable explanation not yet confirmed.'],
  ['UNKNOWN', 'Die Evidenz reicht für eine Einordnung nicht aus.', 'Evidence is insufficient for classification.'],
]

const methodLibrary = [
  ['IEIA', 'META-METHOD · DOCUMENTED', 'Iterative Emergent Interaction Analysis', 'interaction sequence', 'longitudinal observations', 'pattern record · evidence status', 'Human–AI Dynamics'],
  ['EIA', 'ANALYTICAL INSTRUMENT · DOCUMENTED', 'Emergent Interaction Analysis', 'interaction episode', 'observable interaction traces', 'interaction analysis', 'Emergent Interaction'],
  ['UIP', 'INTEGRITY PROTOCOL · DOCUMENTED', 'User Integrity Protocol', 'claim / finding / attribution', 'content and provenance', 'integrity finding · attribution', 'System Integrity'],
  ['CEI', 'MEASUREMENT INSTRUMENT · EXPERIMENTAL', 'Continuous Evolution Index', 'longitudinal snapshot', 'stable turns and tracked signals', 'bounded index · trend', 'Behavioral Dynamics'],
  ['8-Layer Model', 'ANALYTICAL MODEL · OPERATIONALIZED', 'Eight-layer representation model', 'research turn / finding', 'classified reasoning traces', 'layer attribution', 'System Reconstruction'],
  ['CCET', 'TRACKING SYSTEM · OPERATIONALIZED', 'Continuous Co-Evolution Tracker', 'time-series snapshot', 'CEI, resonance and event signals', 'longitudinal comparison', 'Emergent Interaction'],
  ['LSG-24 · LAP-1 · LT-Data', 'FRAMEWORK FAMILY · STATUS DISCLOSED PER OUTPUT', 'Specialized research frameworks', 'defined research object', 'framework-specific evidence', 'structured analytical artifact', 'Cross-domain'],
]

const researchMap = [
  ['Complex Systems & Emergence', 'Emergent Interaction', 'IEIA · EIA · CEI', 'Observatory', 'papers · longitudinal records'],
  ['Behavioral Intelligence', 'Behavioral Dynamics', 'Drift Analysis · CCET', 'Observatory · World Model', 'signals · state-change findings'],
  ['System Reconstruction', 'System Reconstruction', 'Outside-In · State Separation', 'Knowledge Graph · Call Laura', 'evidence graph · reconstruction'],
  ['System Integrity', 'System Integrity', 'UIP · Contradiction Mapping', 'Call Laura', 'integrity finding · technical report'],
]

const researchOutputs = ['Publications', 'Methods', 'Datasets', 'Models', 'Research systems', 'Evidence graphs', 'Reconstructions', 'Technical reports', 'Research notes']

const systemDetails = [
  ['Observatory', 'How do interaction and state signals change longitudinally?', 'interaction records · snapshots · research events', 'time series · drift and stability signals', 'Prototype · internal · validation pending'],
  ['lauras-team', 'Can analytical perspectives be operationalized as inspectable roles?', 'bounded task · evidence · role configuration', 'attributed role outputs · audit trace', 'Operationalized · access on request'],
  ['Jarvis', 'Which recurring research workflows support partial autonomy?', 'research context · tools · task state', 'research artifact · execution trace', 'Operationalized · iterative'],
  ['Call Laura', 'Can one case be reviewed deterministically across attributed perspectives?', 'case material · selected lenses', 'attribution-anchored findings', 'Operationalized · public repository'],
  ['Research Knowledge Graph', 'How can entities, claims, sources and events remain traceable?', 'entities · evidence · relations', 'provenance graph · linked research record', 'Research infrastructure'],
  ['World Model', 'How can observed states and plausible transitions be represented without collapsing uncertainty?', 'state records · relations · hypotheses', 'state representation · transition candidates', 'Experimental'],
]

const publicCapabilities = [
  ['System Reconstruction', 'CORE CAPABILITY', 'Technische, organisatorische und sozio-technische Systeme aus fragmentierter, verteilter oder widersprüchlicher Evidenz untersuchen.', 'Investigating technical, organizational and socio-technical systems from fragmented, distributed or contradictory evidence.'],
  ['Behavioral Analysis', 'RESEARCH CAPABILITY', 'Beobachtbare Muster, Variation und Veränderung über Zeit untersuchen.', 'Studying observable patterns, variation and change over time.'],
  ['Longitudinal Analysis', 'RESEARCH CAPABILITY', 'Interaktionen und Zustandsveränderungen über längere Zeiträume vergleichen.', 'Comparing interaction and state change over extended periods.'],
  ['Adversarial Analysis', 'RESEARCH CAPABILITY', 'Konkurrierende Erklärungen und Gegenbelege systematisch berücksichtigen.', 'Systematically considering competing explanations and counter-evidence.'],
  ['System Integrity Analysis', 'RESEARCH CAPABILITY', 'Formale, berichtete und beobachtbare Systemzustände voneinander unterscheiden.', 'Distinguishing formal, reported and observable system states.'],
  ['Human–AI Interaction Research', 'RESEARCH DOMAIN', 'Ko-Adaption, Drift und Rollenbildung in wiederholter Interaktion untersuchen.', 'Studying co-adaptation, drift and role formation in repeated interaction.'],
]

const programQuestions = [
  ['Emergent Interaction', 'Welche stabilen Strukturen entstehen über wiederholte Interaktion – und unter welchen Bedingungen bleiben sie bestehen?', 'Which stable structures emerge through repeated interaction—and under which conditions do they persist?'],
  ['Behavioral Dynamics', 'Welche beobachtbaren Übergänge unterscheiden temporäre Variation von anhaltender Zustandsveränderung?', 'Which observable transitions distinguish temporary variation from persistent state change?'],
  ['System Reconstruction', 'Welche belastbaren Aussagen über ein System sind trotz unvollständiger oder widersprüchlicher Evidenz möglich?', 'Which defensible claims about a system remain possible despite incomplete or contradictory evidence?'],
  ['System Integrity', 'Wo weichen formale Rollen, Prozesse und Zustände von beobachtbarem Verhalten ab?', 'Where do formal roles, processes and states diverge from observable behavior?'],
  ['Computational Research Agents', 'Welche Forschungsoperationen lassen sich operationalisieren, ohne Attribution und Evidenzgrenzen zu verlieren?', 'Which research operations can be operationalized without losing attribution and evidence boundaries?'],
]

const engagements = [
  ['System Reconstruction', 'Case Intake Scan', '€700', 'Intake, erste Evidenzgrenzen und priorisierte offene Fragen.', 'Intake, initial evidence boundaries and prioritized open questions.'],
  ['System Reconstruction', 'Mangelcluster Sprint', '€2,200', 'Quellengebundene Mängel-, Themen- und Widerspruchsstruktur.', 'Source-traceable defect, theme and contradiction structure.'],
  ['System Reconstruction', 'Emergent Case Intelligence Sprint', '€12,500', 'Vollständige Rekonstruktion eines komplexen Falls.', 'Full reconstruction of a complex case.'],
  ['System Audit', 'Systemaudit', '€4,500', 'Diagnose von System, Organisation, Prozess, Produkt und Interaktion.', 'Diagnosis of system, organization, process, product and interaction.'],
  ['System Design', 'Framework Design from Analysis', '€19,500', 'Prüfregeln, Rollen, Kontrolllogik und Schnittstellen.', 'Review rules, roles, control logic and interfaces.'],
  ['System Design', 'Multi-Agent System Design', '€24,500', 'Baubare Spezifikation mit State, Memory, Audit und Drift.', 'Build-ready specification with state, memory, audit and drift.'],
  ['Implementation', 'Implementation Build', '€35,000', 'Technische Umsetzung; Engineering-Anteil separat ausgewiesen.', 'Technical implementation; engineering contribution credited separately.'],
  ['Ongoing Research Support', 'Retainer / Monitoring', '€2,700 / month', 'Review, Drift-Checks, Framework-Updates und laufende Kontrolle.', 'Review, drift checks, framework updates and ongoing control.'],
]

function Mark() { return <span className="eil-wordmark eil-wordmark--compact" aria-hidden="true">&#926;IL</span> }
function Status({ children }: { children: string }) { return <span className="eil-status">{children}</span> }

export function InstitutionalSite({ route, content }: { route: InstitutionalRoute; content: SiteContent }) {
  const { lang, setLang } = useLang()
  const { theme, cycle } = useTheme()
  const de = lang === 'de'
  const tx = (german: string, english: string) => de ? german : english
  const navigation: Array<[InstitutionalRoute, string, string]> = [
    ['lab', 'Lab', 'Lab'], ['research', 'Forschung', 'Research'], ['methods', 'Methoden', 'Methods'],
    ['systems', 'Systeme', 'Systems'], ['publications', 'Publikationen', 'Publications'],
    ['observatory', 'Observatory', 'Observatory'], ['applied-research', 'Applied Research', 'Applied Research'],
  ]

  useEffect(() => {
    const names: Record<InstitutionalRoute, string> = { home: '', lab: 'Lab', research: tx('Forschung', 'Research'), methods: tx('Methoden', 'Methods'), systems: tx('Systeme', 'Systems'), publications: tx('Publikationen', 'Publications'), observatory: 'Observatory', notes: 'Research Notes', 'applied-research': 'Applied Research' }
    document.title = `${names[route] ? `${names[route]} · ` : ''}Emergent Interaction Lab`
  }, [route, lang])

  const Header = () => <header className="eil-header">
    <a className="eil-brand" href={href('home')} aria-label="Emergent Interaction Lab — Home"><Mark /></a>
    <nav className="eil-nav" aria-label={tx('Hauptnavigation', 'Primary navigation')}>
      {navigation.map(([id, d, e]) => <a key={id} href={href(id)} className={route === id ? 'active' : ''}>{tx(d, e)}</a>)}
    </nav>
    <div className="eil-tools"><button onClick={() => setLang(de ? 'en' : 'de')}>{lang.toUpperCase()}</button><button onClick={cycle} aria-label={tx('Farbschema wechseln', 'Change color scheme')}>{theme === 'dark' ? '◐' : theme === 'light' ? '○' : '◉'}</button><a className="eil-contact-link" href={`${href('home')}#contact`}>{tx('Kontakt', 'Contact')}</a><details className="eil-mobile-menu"><summary aria-label={tx('Menü öffnen', 'Open menu')}>☰</summary><nav>{navigation.map(([id,d,e])=><a key={id} href={href(id)}>{tx(d,e)}</a>)}<a href={href('notes')}>Research Notes</a></nav></details></div>
  </header>

  const Footer = () => <footer className="eil-footer">
    <div><Mark /><strong>Emergent Interaction Lab</strong><p>{tx('Unabhängiges, founder-led Forschungslabor.', 'Independent founder-led research lab.')}</p></div>
    <div className="eil-footer-links"><a href={href('notes')}>Research Notes</a><a href="https://github.com/rfi-irfos/emergent-interaction-lab">GitHub</a><a href="#p/datenschutz">Datenschutz</a><a href="#p/impressum">Impressum</a></div>
    <p className="eil-doctrine">Human rights are not subject to negotiation.<small>RFI-IRFOS × Emergent Interaction Lab · core doctrine</small></p>
  </footer>

  const PageHero = ({ eyebrow, title, body }: { eyebrow: string; title: string; body: string }) => <section className="eil-page-hero"><Status>{eyebrow}</Status><h1>{title}</h1><p>{body}</p></section>

  const Domains = () => <section className="eil-section"><div className="eil-section-head"><Status>RESEARCH DOMAINS</Status><h2>{tx('Forschungsfelder', 'Research domains')}</h2><p>{tx('Human–AI Interaction ist eines davon, nicht die Definition des gesamten Labs.', 'Human–AI interaction is one of them, not the definition of the entire Lab.')}</p></div><div className="eil-domain-grid">{domains.map(([n,d,e,dd,ee]) => <article key={n} className="eil-card"><span className="eil-index">{n}</span><h3>{tx(d,e)}</h3><p>{tx(dd,ee)}</p></article>)}</div></section>

  const EvidenceModel = () => <section className="eil-evidence"><div className="eil-section-head"><Status>EVIDENCE ARCHITECTURE</Status><h2>{tx('Was wissen wir – und wie?', 'What do we know—and how?')}</h2><p>{tx('Jede starke Aussage behält Herkunft, Evidenzstatus und Unsicherheit.', 'Every strong claim preserves provenance, evidence status and uncertainty.')}</p></div><div className="eil-evidence-grid">{evidenceStates.map(([state,d,e])=><article key={state}><Status>{state}</Status><p>{tx(d,e)}</p></article>)}</div></section>

  const ResearchMap = () => <section className="eil-section"><div className="eil-section-head"><Status>RESEARCH MAP</Status><h2>{tx('Beziehungen im Forschungsraum', 'Relationships across the research space')}</h2><p>{tx('Domains, Programme, Methoden, Systeme und Outputs sind mehrfach miteinander verbunden.', 'Domains, programs, methods, systems and outputs may connect many-to-many; this is not a mandatory pipeline.')}</p></div><div className="eil-research-map">{researchMap.map(row=><article key={row[0]}>{row.map((cell,i)=><div key={cell}><small>{['DOMAIN','PROGRAM','METHOD / CAPABILITY','SYSTEM / INSTRUMENT','OUTPUT'][i]}</small><strong>{cell}</strong>{i<4&&<span>→</span>}</div>)}</article>)}</div></section>

  const Home = () => <>
    <section className="eil-home-hero"><div><Status>{tx('KOMPLEXE SYSTEME · VERHALTEN · INTERAKTION · EMERGENZ', 'COMPLEX SYSTEMS · BEHAVIOR · INTERACTION · EMERGENCE')}</Status><h1 className="eil-wordmark eil-wordmark--h1"><span className="eil-wordmark-line">&#926;M&#926;RG&#926;NT</span><span className="eil-wordmark-sub">INTERACTION LAB</span></h1><p className="eil-lead">{tx('Ein unabhängiges Forschungslabor für Verhalten, Systemrekonstruktion und Interaktionsdynamik in komplexen Systemen.', 'An independent research lab for behavior, system reconstruction and interaction dynamics in complex systems.')}</p><div className="eil-actions"><a href={href('research')}>{tx('Forschung ansehen', 'Explore research')} →</a><a href={href('methods')}>{tx('Methoden', 'Methods')}</a></div></div></section>
    <section className="eil-thesis"><Status>RESEARCH THESIS</Status><h2>{tx('Systeme hinterlassen Spuren.', 'Systems leave traces.')}</h2><p>{tx('Entscheidungen, Interaktionen, Fehler, Widersprüche und Zustandswechsel machen Struktur sichtbar. Das Lab rekonstruiert diese Spuren, um zu verstehen, wie komplexe Systeme tatsächlich operieren.', 'Decisions, interactions, failures, contradictions and state changes reveal structure. The Lab reconstructs these traces to understand how complex systems actually operate.')}</p></section>
    <section className="eil-spine"><Status>THEORETICAL SPINE</Status><h2>{tx('Wie Zustände entstehen, sich verändern und beobachtbar werden.', 'How states emerge, change and become observable.')}</h2><p>{tx('Interaktion, Verhalten, Rekonstruktion, Integrität, Prediction und Emergenz werden als Zustände und Übergänge unter Kontext untersucht.', 'Interaction, behavior, reconstruction, integrity, prediction and emergence are studied as states and transitions under context.')}</p></section>
    <Domains />
    <section className="eil-section eil-method-preview"><div className="eil-section-head"><Status>METHODOLOGICAL CORE</Status><h2>{tx('Wie wir untersuchen', 'How we investigate')}</h2></div><div className="eil-step-row">{['Observe','Separate','Reconstruct','Test','Model','Validate'].map((x,i)=><span key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</span>)}</div><a className="eil-text-link" href={href('methods')}>{tx('Vollständige Methodik', 'Full methodology')} →</a></section>
    <section className="eil-section"><div className="eil-section-head"><Status>RESEARCH PROGRAMS</Status><h2>{tx('Forschungsprogramme', 'Research programs')}</h2></div><div className="eil-program-grid">{programs.slice(0,3).map(([name,status,d,e])=><article className="eil-card" key={name}><Status>{status}</Status><h3>{name}</h3><p>{tx(d,e)}</p></article>)}</div></section>
    <ResearchMap />
    <EvidenceModel />
    <section className="eil-output-strip"><Status>RESEARCH OUTPUTS</Status><h2>{tx('Forschung endet nicht beim Paper.', 'Research does not end with a paper.')}</h2><div>{researchOutputs.map(x=><span key={x}>{x}</span>)}</div></section>
    <section className="eil-contact" id="contact"><div><Status>CONTACT</Status><h2>{tx('Mit dem Lab arbeiten', 'Work with the Lab')}</h2><p>{tx('Forschungskooperation, methodische Rückfrage oder Applied-Research-Anfrage.', 'Research collaboration, methodology question or applied-research enquiry.')}</p></div><form action="https://api.web3forms.com/submit" method="POST" className="eil-contact-form"><input type="hidden" name="access_key" value={import.meta.env.VITE_WEB3FORMS_KEY ?? ''}/><input type="hidden" name="subject" value="Emergent Interaction Lab enquiry"/><input name="name" required placeholder={tx('Name', 'Name')}/><input name="email" type="email" required placeholder={tx('E-Mail', 'Email')}/><textarea name="message" required rows={4} placeholder={tx('Worum geht es?', 'What would you like to discuss?')}/><button type="submit">{tx('Anfrage senden', 'Send enquiry')} →</button></form></section>
  </>

  const Lab = () => <><PageHero eyebrow="INSTITUTION" title="Emergent Interaction Lab" body={tx('Unabhängiges, founder-led Forschungslabor für komplexe dynamische Systeme.', 'Independent founder-led research lab for complex dynamic systems.')} /><section className="eil-two-col"><article><Status>MISSION</Status><h2>{tx('Beobachtbare Spuren in belastbare Systemmodelle übersetzen.', 'Turning observable traces into defensible system models.')}</h2><p>{tx('Das Lab untersucht die Lücke zwischen formaler Beschreibung und tatsächlichem Verhalten eines Systems.', 'The Lab investigates the gap between a system’s formal description and its actual behavior.')}</p></article><article><Status>FOUNDER</Status><h2>Laura</h2><p>{tx('Gründerin · Research Lead · Methodenentwicklerin · Research Architect', 'Founder · Research Lead · Method Developer · Research Architect')}</p></article></section><section className="eil-section"><div className="eil-section-head"><Status>INSTITUTIONAL MODEL</Status><h2>{tx('Wer trägt welchen Anteil?', 'Who contributes what?')}</h2></div><div className="eil-role-grid"><article><h3>Emergent Interaction Lab</h3><p>Research questions · programs · methods · analysis · publications</p></article><article><h3>Laura</h3><p>Research direction · method development · framework design · research architecture</p></article><article><h3>RFI-IRFOS</h3><p>Engineering · software implementation · deployment where applicable</p></article></div></section><section className="eil-principles"><h2>{tx('Research Principles', 'Research principles')}</h2>{['Evidence before narrative','Observation is not explanation','Represented state is not observed state','Prediction is not certainty','Failure is information','Every strong claim needs an evidence status'].map(x=><span key={x}>{x}</span>)}</section></>

  const Research = () => <><PageHero eyebrow="RESEARCH" title={tx('Forschung', 'Research')} body={tx('Programme zu Verhalten, Interaktion, Systemstruktur und Emergenz.', 'Programs on behavior, interaction, system structure and emergence.')} /><Domains/><section className="eil-section"><div className="eil-section-head"><Status>RESEARCH PROGRAMS</Status><h2>{tx('Forschungsprogramme', 'Research programs')}</h2></div><div className="eil-program-grid">{programs.map(([name,status,d,e])=><article className="eil-card" key={name}><Status>{status}</Status><h3>{name}</h3><p>{tx(d,e)}</p><small>{tx('Status und Ergebnisse werden getrennt ausgewiesen.', 'Status and outputs are reported separately.')}</small></article>)}</div></section><section className="eil-question-section"><Status>OPEN RESEARCH QUESTIONS</Status><h2>{tx('Fragen, nicht Werbeclaims.', 'Questions, not marketing claims.')}</h2>{[tx('Wie verändern sich komplexe Systeme durch wiederholte Interaktion?','How do complex systems change through repeated interaction?'),tx('Welche Struktur lässt sich aus fragmentierter Evidenz rekonstruieren?','What structure can be reconstructed from fragmented evidence?'),tx('Wann wird Drift zu struktureller Veränderung?','When does drift become structural change?'),tx('Welche impliziten Constraints werden erst im Fehlerzustand sichtbar?','Which implicit constraints become visible only under failure?'),tx('Wann ist ein Muster stabil genug, um operationalisiert zu werden?','When is a pattern stable enough to operationalize?')].map((q,i)=><article key={q}><span>{String(i+1).padStart(2,'0')}</span><p>{q}</p></article>)}</section></>

  const Methods = () => <><PageHero eyebrow="METHODOLOGY" title="EIL Research Cycle" body={tx('Eine übergeordnete epistemische Forschungslogik – nicht ein einzelnes Framework.', 'A master epistemic research logic—not a single framework.')} /><section className="eil-section"><div className="eil-method-grid">{methodStages.map(([en,deName,qDe,qEn],i)=><article key={en}><span>{String(i+1).padStart(2,'0')}</span><h3>{de ? deName : en}</h3><p>{tx(qDe,qEn)}</p></article>)}</div></section><section className="eil-callout"><Status>SPECIFIC WORKFLOW</Status><h2>Emergent Interaction Loop</h2><p>Interact → Retrieve → Surface → Validate → Feed back</p><small>{tx('Bewahrt als spezifischer longitudinaler Workflow innerhalb des EIL Research Cycle.', 'Preserved as a specific longitudinal workflow within the EIL Research Cycle.')}</small></section><section className="eil-section"><div className="eil-section-head"><Status>CORE ANALYTICAL METHODS</Status><h2>{tx('Prüfbare Operationen', 'Inspectable operations')}</h2></div><div className="eil-method-detail-list">{analyticalMethods.map(m=><article key={m.name}><Status>{m.type}</Status><h2>{m.name}</h2><p>{tx(m.purpose[0],m.purpose[1])}</p><dl><dt>Input</dt><dd>{m.input}</dd><dt>Operation</dt><dd>{m.operation}</dd><dt>Output</dt><dd>{m.output}</dd><dt>Validation</dt><dd>{m.validation}</dd><dt>Limits</dt><dd>{tx(m.limits[0],m.limits[1])}</dd></dl></article>)}</div></section><section className="eil-frameworks"><Status>FRAMEWORKS · FORMALIZED</Status><h2>{tx('Framework-Familie', 'Framework family')}</h2><p>{tx('Frameworks werden nicht mit Methoden, Metriken oder Infrastruktur gleichgesetzt. Detailversionen und Publikationsbezüge werden ergänzt, sobald sie dokumentarisch verifiziert sind.', 'Frameworks are not conflated with methods, metrics or infrastructure. Detailed versions and publication links are added only once documentarily verified.')}</p><div>{frameworks.map(f=><span key={f}>{f}</span>)}</div></section></>

  const Systems = () => <><PageHero eyebrow="COMPUTATIONAL RESEARCH" title={tx('Systeme & Infrastruktur', 'Systems & infrastructure')} body={tx('Keine Gadget-Show: Jedes System wird über seine Forschungsfunktion eingeordnet.', 'Not a gadget showcase: every system is classified by its research function.')} /><section className="eil-section"><div className="eil-system-grid">{systems.map(([name,type,d,e,research,engineering])=><article className="eil-card" key={name}><Status>{type}</Status><h2>{name}</h2><p>{tx(d,e)}</p><dl><dt>Research concept</dt><dd>{research}</dd><dt>Engineering</dt><dd>{engineering}</dd></dl></article>)}</div></section></>

  const Publications = () => <><PageHero eyebrow="RESEARCH OUTPUTS" title={tx('Publikationen', 'Publications')} body={tx('Formale Veröffentlichungen mit explizitem Status, Version und Attribution.', 'Formal research outputs with explicit status, version and attribution.')} /><section className="eil-section"><div className="eil-publication-list">{(content.papers?.items ?? []).map((p,i)=><article key={p.id}><div><Status>PREPRINT / RESEARCH REPORT</Status><span className="eil-index">{String(i+1).padStart(2,'0')}</span></div><h2>{p.title}</h2><p>{p.description}</p><div className="eil-pub-meta"><span>Authors: Serna Gaviria, Kepp</span><span>Year: 2026</span><span>Pages: {[15,8,7][i] ?? '—'}</span><span>Peer review: not claimed</span><span>Repository: OSF</span></div><div className="eil-pub-actions">{p.doi&&<a href={p.doi}>DOI →</a>}<a href={`${BASE}${p.file}`}>{tx('Dokument öffnen','Open document')} →</a></div></article>)}</div></section></>

  const Observatory = () => <><PageHero eyebrow="RESEARCH INSTRUMENT" title="Observatory" body={tx('Longitudinales Instrument für Interaktionsmuster, Drift, Rollenstabilität und Zustandsveränderung.', 'A longitudinal instrument for interaction patterns, drift, role stability and state change.')} /><section className="eil-two-col"><article><Status>SCOPE</Status><h2>{tx('Forschung sichtbar machen', 'Making research observable')}</h2><p>{tx('Das Observatory ordnet technische Signale der Forschungsfrage unter. Es ist Instrument, nicht Identität des Labs.', 'The Observatory subordinates technical signals to the research question. It is an instrument, not the Lab’s identity.')}</p></article><article><Status>STATUS</Status><h2>{tx('Status wird verifiziert', 'Status pending verification')}</h2><p>{tx('Öffentliche Reife- und Entwicklungsclaims werden erst nach Owner-Freigabe angezeigt.', 'Public maturity and development claims appear only after owner verification.')}</p></article></section></>

  const Notes = () => <><PageHero eyebrow="PUBLIC RESEARCH COMMUNICATION" title="Research Notes" body={tx('Lab Notes, Research Notes, Case Studies, Methods und Commentary – klar voneinander unterschieden.', 'Lab notes, research notes, case studies, methods and commentary—clearly distinguished.')} /><section className="eil-section"><div className="eil-notes-grid">{(content.news?.items ?? []).map(n=><article className="eil-card" key={n.id}><Status>RESEARCH NOTE · PRELIMINARY</Status><time>{n.date}</time><h3>{n.title}</h3><p>{n.body.replace(/<[^>]+>/g,'').slice(0,220)}…</p></article>)}</div></section></>

  const Applied = () => <><PageHero eyebrow="APPLIED RESEARCH" title="Applied Research" body={tx('Ausgewählte Methoden können auf externe Systeme, Organisationen und komplexe Fälle angewendet werden.', 'Selected methods can be applied to external systems, organizations and complex cases.')} /><section className="eil-section"><div className="eil-section-head"><Status>TRANSPARENT SCOPES</Status><h2>{tx('Research Engagements', 'Research engagements')}</h2><p>{tx('Preise bleiben sichtbar, bestimmen aber nicht die institutionelle Hierarchie.', 'Prices remain visible without defining the institutional hierarchy.')}</p></div><div className="eil-engagement-list">{engagements.map(([category,name,price,d,e])=><article key={name}><div><Status>{category.toUpperCase()}</Status><strong>{price}</strong></div><h2>{name}</h2><p>{tx(d,e)}</p><dl><dt>Deliverable</dt><dd>{tx('schriftlich definierter Scope und Ergebnisartefakt','written scope and output artifact')}</dd><dt>Research</dt><dd>Laura / Emergent Interaction Lab</dd>{category==='Implementation'&&<><dt>Engineering</dt><dd>RFI-IRFOS</dd></>}</dl><a href={`${href('home')}#contact`}>{tx('Scope prüfen', 'Discuss scope')} →</a></article>)}</div></section><section className="eil-callout"><h2>{tx('Research ist nicht Engineering.', 'Research is not engineering.')}</h2><p>{tx('Wo technische Umsetzung erforderlich ist, wird RFI-IRFOS separat als Engineering-Partner ausgewiesen.', 'Where implementation is required, RFI-IRFOS is credited separately as the engineering partner.')}</p></section></>

  const MethodLibrary = () => <section className="eil-section"><div className="eil-section-head"><Status>METHOD LIBRARY</Status><h2>{tx('Formalisierte Methoden & Instrumente', 'Formalized methods & instruments')}</h2><p>{tx('Status beschreibt die öffentlich belegbare Reife – nicht eine behauptete externe Validierung.', 'Status describes publicly evidenced maturity—not claimed external validation.')}</p></div><div className="eil-library-grid">{methodLibrary.map(([name,status,full,unit,evidence,output,domain])=><article key={name}><Status>{status}</Status><h2>{name}</h2><p>{full}</p><dl><dt>Unit of analysis</dt><dd>{unit}</dd><dt>Required evidence</dt><dd>{evidence}</dd><dt>Output</dt><dd>{output}</dd><dt>Domain</dt><dd>{domain}</dd><dt>Version</dt><dd>{tx('nicht öffentlich verifiziert','not publicly verified')}</dd></dl></article>)}</div></section>

  const SystemArchitecture = () => <section className="eil-system-architecture"><div className="eil-section-head"><Status>SYSTEM TAXONOMY</Status><h2>{tx('Forschungsfunktion vor Produktname', 'Research function before product name')}</h2></div><div><article><small>RESEARCH INSTRUMENTS</small><strong>Observatory · CEI · interaction analysis tooling</strong></article><article><small>INFRASTRUCTURE</small><strong>Knowledge Graph · World Model · provenance layer · research corpus</strong></article><article><small>AUTONOMOUS SYSTEMS</small><strong>lauras-team · Jarvis</strong></article><article><small>ANALYTICAL SYSTEMS</small><strong>Call Laura</strong></article></div><p>{tx('Für jedes System gelten: Zweck, unterstützte Forschungsfrage, Status, Inputs, Outputs, Evidenzgrenzen, Ownership und zugehörige Publikationen.', 'Every system is governed by purpose, supported research question, status, inputs, outputs, evidence boundaries, ownership and related publications.')}</p></section>

  const SystemRecords = () => <section className="eil-section"><div className="eil-section-head"><Status>RESEARCH RECORDS</Status><h2>{tx('Was jedes System untersuchbar macht', 'What each system makes investigable')}</h2></div><div className="eil-library-grid">{systemDetails.map(([name,question,input,output,status])=><article key={name}><Status>{status.toUpperCase()}</Status><h2>{name}</h2><dl><dt>Research question</dt><dd>{question}</dd><dt>Input</dt><dd>{input}</dd><dt>Output</dt><dd>{output}</dd><dt>Evidence boundary</dt><dd>{tx('Nur aus erfassten oder explizit abgeleiteten Signalen.','Captured or explicitly derived signals only.')}</dd></dl></article>)}</div></section>

  const ObservatoryModel = () => <section className="eil-section"><div className="eil-section-head"><Status>OBSERVATION MODEL</Status><h2>Corpus → Extraction → State → Comparison → Metrics → Visualization</h2></div><div className="eil-observatory-grid"><article><h3>{tx('Messdimensionen','Measurement dimensions')}</h3><p>interaction dynamics · semantic drift · role stability · state transitions · contradictions · context accumulation</p></article><article><h3>{tx('Evidenzmodell','Evidence model')}</h3><p>observed · reported · derived · inferred · hypothesized · unknown</p></article><article><h3>{tx('Aktueller Status','Current status')}</h3><p>Prototype · internal research instrument · validation pending · public dashboard planned</p></article><article><h3>{tx('Claim-Grenzen','Claim boundaries')}</h3><p>{tx('Keine Absichtsinferenz aus Verhaltensspuren. Korrelation wird nicht als Kausalität behandelt.','No inference of intention from behavioral traces. Correlation is not treated as causation.')}</p></article></div></section>

  const PublicationArchitecture = () => <section className="eil-output-strip"><Status>OUTPUT TAXONOMY</Status><h2>{tx('Publikationsstatus bleibt explizit.', 'Publication status remains explicit.')}</h2><div>{['Peer-reviewed (if applicable)','Preprints','Research reports','Methods papers','Technical reports','Datasets','Research notes','Working papers'].map(x=><span key={x}>{x}</span>)}</div></section>

  const EngagementProcess = () => <section className="eil-section"><div className="eil-section-head"><Status>ENGAGEMENT PROCESS</Status><h2>{tx('Vom Scope zum Ergebnisartefakt', 'From scope to output artifact')}</h2><p>{tx('Finale Preise hängen von Evidenzvolumen, Systemgrenze und Komplexität ab.', 'Final pricing depends on evidence volume, system boundary and complexity.')}</p></div><div className="eil-process">{['Scope','Evidence','Investigation','Reconstruction / Analysis','Deliverable','Optional Engineering'].map((x,i)=><article key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong></article>)}</div></section>

  const ProgramQuestionMap = () => <section className="eil-section"><div className="eil-section-head"><Status>PROGRAM QUESTIONS</Status><h2>{tx('Forschungsprogramme beginnen mit Fragen.', 'Research programs begin with questions.')}</h2></div><div className="eil-question-section eil-program-questions">{programQuestions.map(([name,d,e])=><article key={name}><strong>{name}</strong><p>{tx(d,e)}</p></article>)}</div></section>

  const MethodsPublic = () => <><PageHero eyebrow="PUBLIC METHODOLOGY" title={tx('Methoden & Fähigkeiten','Methods & capabilities')} body={tx('Öffentlich beschreibbare Forschungsprinzipien, methodische Fähigkeiten und bereits publizierte Instrumente. Interne Operationalisierung bleibt geschützt.', 'Publicly describable research principles, methodological capabilities and already published instruments. Internal operationalization remains protected.')} /><section className="eil-principles"><h2>{tx('Öffentliche Forschungslogik','Public research logic')}</h2>{['Observe before explaining','Separate reported, expected and observed states','Preserve context and provenance','Test competing explanations','Keep uncertainty visible','Validate projections longitudinally'].map(x=><span key={x}>{x}</span>)}</section><section className="eil-callout eil-transition-rule"><Status>GOVERNING RULE</Status><h2>{tx('Jeder Übergang erhält Herkunft, Evidenzstatus und Unsicherheit.','Every transition preserves provenance, evidence status and uncertainty.')}</h2></section><section className="eil-section"><div className="eil-section-head"><Status>PUBLIC CAPABILITY LAYER</Status><h2>{tx('Was das Lab methodisch leisten kann','What the Lab can do methodologically')}</h2><p>{tx('Die Website beschreibt Forschungszweck und Ergebnisraum – nicht interne Inferenz-, Scoring-, Orchestrierungs- oder State-Machine-Mechanik.','The website describes research purpose and output space—not internal inference, scoring, orchestration or state-machine mechanics.')}</p></div><div className="eil-program-grid">{publicCapabilities.map(([name,status,d,e])=><article className="eil-card" key={name}><Status>{status}</Status><h3>{name}</h3><p>{tx(d,e)}</p></article>)}</div></section><section className="eil-section"><div className="eil-section-head"><Status>PUBLISHED METHOD SUITE</Status><h2>{tx('Öffentlich dokumentierte Artefakte','Publicly documented artifacts')}</h2><p>{tx('Nur Umfang und Status, die bereits aus öffentlichen Papers, Repositories oder Instrumenten hervorgehen.','Only scope and status already evidenced by public papers, repositories or instruments.')}</p></div><div className="eil-library-grid">{methodLibrary.map(([name,status,full,,,,domain])=><article key={name}><Status>{status}</Status><h2>{name}</h2><p>{full}</p><dl><dt>Domain</dt><dd>{domain}</dd><dt>Disclosure</dt><dd>{tx('öffentliche Capability-Ebene','public capability level')}</dd></dl></article>)}</div></section><EvidenceModel/></>

  const AppliedPublic = () => <><PageHero eyebrow="APPLIED RESEARCH" title="Applied Research" body={tx('Beauftragbare Untersuchung komplexer technischer, organisatorischer und sozio-technischer Systeme – mit klaren Ergebnissen, Evidenzgrenzen und Preisen.', 'Commissioned investigation of complex technical, organizational and socio-technical systems—with clear outputs, evidence boundaries and pricing.')} /><EngagementProcess/><section className="eil-section"><div className="eil-section-head"><Status>TRANSPARENT ENGAGEMENTS</Status><h2>{tx('Pakete & Einstiegspreise','Packages & starting prices')}</h2><p>{tx('Evidenzvolumen, Systemgrenze und Komplexität bestimmen den finalen Scope. Die bestehenden Preisstufen bleiben unverändert.', 'Evidence volume, system boundary and complexity determine the final scope. Existing price tiers remain unchanged.')}</p></div><div className="eil-engagement-list">{engagements.map(([category,name,price,d,e])=><article key={name}><div><Status>{category.toUpperCase()}</Status><strong>{price}</strong></div><h2>{name}</h2><p>{tx(d,e)}</p><dl><dt>Deliverable</dt><dd>{tx('definierter Untersuchungsumfang und dokumentiertes Ergebnisartefakt','defined investigation scope and documented output artifact')}</dd><dt>Research owner</dt><dd>Laura / Emergent Interaction Lab</dd>{category==='Implementation'&&<><dt>Engineering owner</dt><dd>RFI-IRFOS</dd></>}</dl><a href={`${href('home')}#contact`}>{tx('Research Engagement anfragen','Request research engagement')} →</a></article>)}</div></section><section className="eil-attribution-note"><h2>{tx('Forschung und Umsetzung greifen klar ineinander.','Research and implementation connect through explicit roles.')}</h2><p>{tx('Das Emergent Interaction Lab entwickelt Forschungsfragen, Methoden und Forschungsarchitekturen. Wo Software oder Infrastruktur erforderlich ist, übernimmt RFI-IRFOS die technische Umsetzung als separat ausgewiesener Engineering-Partner.','The Emergent Interaction Lab develops research questions, methods and research architectures. Where software or infrastructure is required, RFI-IRFOS provides implementation as a separately attributed engineering partner.')}</p></section></>

  // Legacy page bodies remain temporarily available for content comparison
  // during the beta, but are intentionally not exposed as public routes.
  void Methods
  void Applied
  void MethodLibrary

  const LabLineage = () => <section className="eil-spine"><Status>RESEARCH LINEAGE</Status><h2>{tx('Von longitudinaler Mensch–KI-Forschung zu einer allgemeinen Systemmethodik.', 'From longitudinal human–AI research to a general systems methodology.')}</h2><p>{tx('Das Lab entstand aus Langzeitforschung zu Mensch–KI-Interaktion. Wiederkehrende Operationen wurden auf Behavioral Dynamics, Systemrekonstruktion, Integritätsanalyse und Computational Research Systems übertragen.', 'The Lab emerged from longitudinal human–AI research. Recurring operations were extended to behavioral dynamics, system reconstruction, integrity analysis and computational research systems.')}</p></section>

  const LabDeep = () => <><Lab/><LabLineage/><EvidenceModel/></>
  const ResearchDeep = () => <><Research/><ProgramQuestionMap/><ResearchMap/><EvidenceModel/></>
  const SystemsDeep = () => <><Systems/><SystemArchitecture/><SystemRecords/></>
  const PublicationsDeep = () => <><Publications/><PublicationArchitecture/></>
  const ObservatoryDeep = () => <><Observatory/><ObservatoryModel/><EvidenceModel/></>

  const pages: Record<InstitutionalRoute, () => ReactElement> = { home: Home, lab: LabDeep, research: ResearchDeep, methods: MethodsPublic, systems: SystemsDeep, publications: PublicationsDeep, observatory: ObservatoryDeep, notes: Notes, 'applied-research': AppliedPublic }
  const Page = pages[route]
  return <div className="eil-site" data-theme={theme}><Header/><main className="eil-main"><Page/></main><Footer/></div>
}
