import { useEffect, useState } from "react";

// EIL static-first research site
// Crawler gets static HTML; this React layer handles client-side nav + preview.
// Data source: index.json (generated by build-static.mjs from backend snapshot)

function useRoute() {
  const [route, setRoute] = useState(window.location.pathname);
  useEffect(() => {
    const onPop = () => setRoute(window.location.pathname);
    window.addEventListener("popstate", onPop);
    return () => window.removeEventListener("popstate", onPop);
  }, []);
  return route;
}

function parseRoute(path: string): { locale: string; type: string; slug: string | null } {
  // /en/research/<slug>/  /de/evidence/<slug>/  /  /en/  /de/
  const m = path.match(/^\/(en|de)\/([a-z]+)\/([^/]+)\/?$/);
  if (m) return { locale: m[1], type: m[2], slug: m[3] };
  if (path === "/" || path === "/en/" || path === "/de/") {
    const locale = path.startsWith("/de") ? "de" : "en";
    return { locale, type: "home", slug: null };
  }
  return { locale: "en", type: "unknown", slug: null };
}

function EntityView({ data, locale, type, slug }: { data: any; locale: string; type: string; slug: string | null }) {
  const key = type === "research" ? "research_programs"
    : type === "evidence" ? "case_studies"
    : type === "publications" ? "publications"
    : type === "frameworks" ? "frameworks"
    : type === "systems" ? "systems"
    : type === "methods" ? "methods"
    : type === "datasets" ? "datasets"
    : type === "laura" ? "profiles" : null;
  if (!key) return <p>Not found</p>;
  const items = data[key] || [];
  const item = items.find((e: any) => e.slug === slug);
  if (!item) return <p>Not found</p>;
  const title = item[`title_${locale}`] || item.title_en;
  const desc = item[`description_${locale}`] || item.description_en || "";
  return (
    <main>
      <h1>{title}</h1>
      <p>{desc}</p>
      <nav><a href="/en/">English</a> · <a href="/de/">Deutsch</a></nav>
    </main>
  );
}

function Home({ data, locale }: { data: any; locale: string }) {
  const lists: [string, string, string][] = [
    ["Research Programs", "research_programs", "research"],
    ["Frameworks", "frameworks", "frameworks"],
    ["Systems", "systems", "systems"],
    ["Methods", "methods", "methods"],
    ["Evidence", "case_studies", "evidence"],
    ["Publications", "publications", "publications"],
    ["Datasets", "datasets", "datasets"],
    ["Laura", "profiles", "laura"],
  ];
  return (
    <main>
      <h1>Emergent Interaction Lab</h1>
      <p>Complex Systems · Interaction · Intelligence · Architecture</p>
      {lists.map(([label, key, route]) => (
        <section key={key}>
          <h2>{label}</h2>
          <ul>
            {(data[key] || []).map((e: any) => (
              <li key={e.id}><a href={`/${locale}/${route}/${e.slug}/`}>{e[`title_${locale}`] || e.title_en}</a></li>
            ))}
          </ul>
        </section>
      ))}
      <nav><a href="/en/">English</a> · <a href="/de/">Deutsch</a></nav>
    </main>
  );
}

export default function App() {
  const route = useRoute();
  const [data, setData] = useState<any>(null);

  useEffect(() => {
    fetch("/index.json")
      .then((r) => r.json())
      .then(setData)
      .catch(() => setData({}));
  }, []);

  if (!data) return <div>Loading…</div>;
  const r = parseRoute(route);
  const loc = r.locale || "en";

  if (r.type === "home") return <Home data={data} locale={loc} />;
  if (r.type === "unknown") return <main><h1>404</h1><nav><a href="/en/">English</a> · <a href="/de/">Deutsch</a></nav></main>;
  return <EntityView data={data} locale={loc} type={r.type} slug={r.slug} />;
}
